[package]
authors = ["IgnorantCoder <fr052123@gmail.com>"]
edition = "2018"
name = "suzume"
version = "0.1.0"
[dependencies]
serde = "1.0.81"
serde_json = "1.0.33"
serde_derive = "1.0.81"
reqwest = "0.9.5"
failure = "0.1.3"
base64 = "0.10.0"
time = "0.1.41"
openssl = "0.10.15"

